### ISSUE TITLE
org.springframework.data.cassandra.CassandraConnectionFailureException: Query; CQL 

### ISSUE THREAD

**Issue by SabyasachiRana** [aws/aws-sigv4-auth-cassandra-java-driver-plugin#17]
org.springframework.data.cassandra.CassandraConnectionFailureException: Query; CQL [com.datastax.oss.driver.internal.core.cql.DefaultSimpleStatement@32c99126]; No node was available to execute the query; nested exception is com.datastax.oss.driver.api.core.NoNodeAvailableException: No node was available to execute the query

**Comment by bhouse99** [comment]
Hi!  Thanks for bringing this to our attention.

I have built a quick prototype in spring and was able to communicate with Amazon Keyspaces via the sigv4 plugin.  Could you give us a few more details about your use case?  Specifically if you could tell us the version of the Cassandra driver and spring-data you are using, the code you are using for a connection, and possibly a stack trace? 

This exception is a general one and usually indicates a problem with the initial connection.. This could be due to a variety of issues.  You might get a faster response if you opened an AWS forum post...  This would also permit you to send  additional information via a direct message.  https://forums.aws.amazon.com

Thanks!

Brian
